<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto

namespace Business\Hyperf\Rpc\Grpc\Protobuf\Message;

/**
 * The service definition.
 *
 * Protobuf type <code>grpc.Grpc</code>
 */
interface GrpcInterface
{
    /**
     * Method <code>transIn</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transIn(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOut</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOut(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transInRevert</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transInRevert(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOutRevert</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOutRevert(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transInConfirm</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transInConfirm(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOutConfirm</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOutConfirm(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>xaNotify</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function xaNotify(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply $request);

    /**
     * Method <code>transInXa</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transInXa(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOutXa</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOutXa(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transInTcc</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transInTcc(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOutTcc</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOutTcc(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transInTccNested</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transInTccNested(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transInBSaga</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transInBSaga(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOutBSaga</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOutBSaga(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transInRevertBSaga</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transInRevertBSaga(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOutRevertBSaga</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOutRevertBSaga(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOutHeaderYes</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOutHeaderYes(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOutHeaderNo</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOutHeaderNo(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transInRedis</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transInRedis(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOutRedis</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOutRedis(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transInRevertRedis</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transInRevertRedis(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>transOutRevertRedis</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function transOutRevertRedis(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>queryPrepared</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function queryPrepared(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>queryPreparedB</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function queryPreparedB(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

    /**
     * Method <code>queryPreparedRedis</code>
     *
     * @param \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request
     * @return \Business\Hyperf\Rpc\Grpc\Protobuf\Message\Reply
     */
    public function queryPreparedRedis(\Business\Hyperf\Rpc\Grpc\Protobuf\Message\Req $request);

}

